// Almanca'nın en sık kullanılan fiilleri — tüm temel formlar + her form için örnek cümle
const verbs = [
  // Yardımcı fiiller
  { inf:"sein", tr:"olmak", type:"auxiliary", praesens:"ist", praeteritum:"war", partizip:"gewesen", aux:"sein",
    ex:{ inf:{de:"Ich will glücklich sein.",tr:"Mutlu olmak istiyorum."}, praesens:{de:"Er ist zu Hause.",tr:"Evde."}, praeteritum:{de:"Sie war gestern krank.",tr:"Dün hastaydı."}, partizip:{de:"Ich bin in Berlin gewesen.",tr:"Berlin'de bulundum."} } },
  { inf:"haben", tr:"sahip olmak", type:"auxiliary", praesens:"hat", praeteritum:"hatte", partizip:"gehabt", aux:"haben",
    ex:{ inf:{de:"Man muss Geduld haben.",tr:"Sabırlı olmak gerek."}, praesens:{de:"Er hat viel Zeit.",tr:"Çok vakti var."}, praeteritum:{de:"Sie hatte Hunger.",tr:"Acıkmıştı."}, partizip:{de:"Ich habe Glück gehabt.",tr:"Şanslıydım."} } },
  { inf:"werden", tr:"olmak (süreç)", type:"auxiliary", praesens:"wird", praeteritum:"wurde", partizip:"geworden", aux:"sein",
    ex:{ inf:{de:"Er will Arzt werden.",tr:"Doktor olmak istiyor."}, praesens:{de:"Sie wird müde.",tr:"Yoruluyor."}, praeteritum:{de:"Es wurde kalt.",tr:"Hava soğudu."}, partizip:{de:"Er ist Vater geworden.",tr:"Baba oldu."} } },

  // Modal fiiller
  { inf:"können", tr:"-ebilmek", type:"modal", praesens:"kann", praeteritum:"konnte", partizip:"gekonnt", aux:"haben",
    ex:{ inf:{de:"Das muss man können.",tr:"Bunu yapabilmek gerek."}, praesens:{de:"Er kann Deutsch.",tr:"Almanca biliyor."}, praeteritum:{de:"Ich konnte nicht kommen.",tr:"Gelemedim."}, partizip:{de:"Das habe ich nie gekonnt.",tr:"Bunu hiç yapamadım."} } },
  { inf:"müssen", tr:"zorunda olmak", type:"modal", praesens:"muss", praeteritum:"musste", partizip:"gemusst", aux:"haben",
    ex:{ inf:{de:"Das Essen muss warm sein.",tr:"Yemek sıcak olmalı."}, praesens:{de:"Ich muss jetzt gehen.",tr:"Şimdi gitmem gerek."}, praeteritum:{de:"Er musste arbeiten.",tr:"Çalışmak zorundaydı."}, partizip:{de:"Ich habe das gemusst.",tr:"Bunu yapmak zorunda kaldım."} } },
  { inf:"wollen", tr:"istemek", type:"modal", praesens:"will", praeteritum:"wollte", partizip:"gewollt", aux:"haben",
    ex:{ inf:{de:"Man muss nur wollen.",tr:"Sadece istemek yeter."}, praesens:{de:"Sie will reisen.",tr:"Seyahat etmek istiyor."}, praeteritum:{de:"Ich wollte dich anrufen.",tr:"Seni aramak istemiştim."}, partizip:{de:"Das habe ich so gewollt.",tr:"Bunu böyle istedim."} } },
  { inf:"sollen", tr:"-meli", type:"modal", praesens:"soll", praeteritum:"sollte", partizip:"gesollt", aux:"haben",
    ex:{ inf:{de:"Was soll das sein?",tr:"Bu ne olmalı?"}, praesens:{de:"Du sollst pünktlich sein.",tr:"Dakik olmalısın."}, praeteritum:{de:"Ich sollte früher kommen.",tr:"Daha erken gelmeliydim."}, partizip:{de:"Das habe ich nicht gesollt.",tr:"Bunu yapmamalıydım."} } },
  { inf:"dürfen", tr:"izinli olmak", type:"modal", praesens:"darf", praeteritum:"durfte", partizip:"gedurft", aux:"haben",
    ex:{ inf:{de:"Hier darf man nicht rauchen.",tr:"Burada sigara içilmez."}, praesens:{de:"Darf ich herein?",tr:"Girebilir miyim?"}, praeteritum:{de:"Als Kind durfte ich viel.",tr:"Çocukken çok izinliydim."}, partizip:{de:"Das hat er nicht gedurft.",tr:"Buna izin verilmemişti."} } },
  { inf:"mögen", tr:"hoşlanmak", type:"modal", praesens:"mag", praeteritum:"mochte", partizip:"gemocht", aux:"haben",
    ex:{ inf:{de:"Ich mag Schokolade.",tr:"Çikolata severim."}, praesens:{de:"Er mag kein Gemüse.",tr:"Sebzeden hoşlanmaz."}, praeteritum:{de:"Sie mochte ihn nicht.",tr:"Ondan hoşlanmazdı."}, partizip:{de:"Das habe ich immer gemocht.",tr:"Bunu hep sevdim."} } },

  // Düzensiz fiiller
  { inf:"gehen", tr:"gitmek", type:"irregular", praesens:"geht", praeteritum:"ging", partizip:"gegangen", aux:"sein",
    ex:{ inf:{de:"Ich möchte spazieren gehen.",tr:"Yürüyüşe çıkmak istiyorum."}, praesens:{de:"Er geht jeden Tag zur Arbeit.",tr:"Her gün işe gidiyor."}, praeteritum:{de:"Wir gingen ins Kino.",tr:"Sinemaya gittik."}, partizip:{de:"Ich bin nach Hause gegangen.",tr:"Eve gittim."} } },
  { inf:"kommen", tr:"gelmek", type:"irregular", praesens:"kommt", praeteritum:"kam", partizip:"gekommen", aux:"sein",
    ex:{ inf:{de:"Kannst du morgen kommen?",tr:"Yarın gelebilir misin?"}, praesens:{de:"Er kommt aus Berlin.",tr:"Berlin'den geliyor."}, praeteritum:{de:"Sie kam zu spät.",tr:"Geç geldi."}, partizip:{de:"Ich bin gerade gekommen.",tr:"Az önce geldim."} } },
  { inf:"sehen", tr:"görmek", type:"irregular", praesens:"sieht", praeteritum:"sah", partizip:"gesehen", aux:"haben",
    ex:{ inf:{de:"Ich will den Film sehen.",tr:"Filmi izlemek istiyorum."}, praesens:{de:"Er sieht gut aus.",tr:"İyi görünüyor."}, praeteritum:{de:"Ich sah ihn gestern.",tr:"Onu dün gördüm."}, partizip:{de:"Hast du das gesehen?",tr:"Bunu gördün mü?"} } },
  { inf:"geben", tr:"vermek", type:"irregular", praesens:"gibt", praeteritum:"gab", partizip:"gegeben", aux:"haben",
    ex:{ inf:{de:"Kannst du mir das geben?",tr:"Bunu bana verebilir misin?"}, praesens:{de:"Er gibt mir das Buch.",tr:"Bana kitabı veriyor."}, praeteritum:{de:"Sie gab ihm einen Kuss.",tr:"Ona bir öpücük verdi."}, partizip:{de:"Ich habe dir das gegeben.",tr:"Bunu sana verdim."} } },
  { inf:"nehmen", tr:"almak", type:"irregular", praesens:"nimmt", praeteritum:"nahm", partizip:"genommen", aux:"haben",
    ex:{ inf:{de:"Ich muss die Medizin nehmen.",tr:"İlacı almam lazım."}, praesens:{de:"Er nimmt den Bus.",tr:"Otobüse biniyor."}, praeteritum:{de:"Sie nahm den Schlüssel.",tr:"Anahtarı aldı."}, partizip:{de:"Ich habe Urlaub genommen.",tr:"İzin aldım."} } },
  { inf:"finden", tr:"bulmak", type:"irregular", praesens:"findet", praeteritum:"fand", partizip:"gefunden", aux:"haben",
    ex:{ inf:{de:"Ich kann ihn nicht finden.",tr:"Onu bulamıyorum."}, praesens:{de:"Er findet das gut.",tr:"Bunu iyi buluyor."}, praeteritum:{de:"Sie fand eine Lösung.",tr:"Bir çözüm buldu."}, partizip:{de:"Ich habe meinen Schlüssel gefunden.",tr:"Anahtarımı buldum."} } },
  { inf:"denken", tr:"düşünmek", type:"irregular", praesens:"denkt", praeteritum:"dachte", partizip:"gedacht", aux:"haben",
    ex:{ inf:{de:"Man muss positiv denken.",tr:"Pozitif düşünmek gerek."}, praesens:{de:"Er denkt an dich.",tr:"Seni düşünüyor."}, praeteritum:{de:"Ich dachte an meine Familie.",tr:"Ailemi düşündüm."}, partizip:{de:"Das habe ich schon gedacht.",tr:"Bunu zaten düşünmüştüm."} } },
  { inf:"bringen", tr:"getirmek", type:"irregular", praesens:"bringt", praeteritum:"brachte", partizip:"gebracht", aux:"haben",
    ex:{ inf:{de:"Soll ich etwas bringen?",tr:"Bir şey getireyim mi?"}, praesens:{de:"Er bringt die Kinder zur Schule.",tr:"Çocukları okula götürüyor."}, praeteritum:{de:"Sie brachte Blumen.",tr:"Çiçek getirdi."}, partizip:{de:"Ich habe Kuchen gebracht.",tr:"Pasta getirdim."} } },
  { inf:"kennen", tr:"tanımak", type:"irregular", praesens:"kennt", praeteritum:"kannte", partizip:"gekannt", aux:"haben",
    ex:{ inf:{de:"Ich will ihn kennen lernen.",tr:"Onunla tanışmak istiyorum."}, praesens:{de:"Er kennt meinen Bruder.",tr:"Kardeşimi tanıyor."}, praeteritum:{de:"Sie kannte den Weg nicht.",tr:"Yolu bilmiyordu."}, partizip:{de:"Wir haben uns lange gekannt.",tr:"Uzun zamandır tanışıyorduk."} } },
  { inf:"wissen", tr:"bilmek", type:"irregular", praesens:"weiß", praeteritum:"wusste", partizip:"gewusst", aux:"haben",
    ex:{ inf:{de:"Ich will es wissen.",tr:"Bunu bilmek istiyorum."}, praesens:{de:"Er weiß die Antwort.",tr:"Cevabı biliyor."}, praeteritum:{de:"Ich wusste es nicht.",tr:"Bilmiyordum."}, partizip:{de:"Das habe ich nicht gewusst.",tr:"Bunu bilmiyordum."} } },
  { inf:"treffen", tr:"buluşmak", type:"irregular", praesens:"trifft", praeteritum:"traf", partizip:"getroffen", aux:"haben",
    ex:{ inf:{de:"Wir wollen uns treffen.",tr:"Buluşmak istiyoruz."}, praesens:{de:"Er trifft sie heute.",tr:"Bugün onunla buluşuyor."}, praeteritum:{de:"Ich traf ihn im Café.",tr:"Onunla kafede buluştum."}, partizip:{de:"Wir haben uns gestern getroffen.",tr:"Dün buluştuk."} } },
  { inf:"lesen", tr:"okumak", type:"irregular", praesens:"liest", praeteritum:"las", partizip:"gelesen", aux:"haben",
    ex:{ inf:{de:"Ich liebe es zu lesen.",tr:"Okumayı seviyorum."}, praesens:{de:"Er liest die Zeitung.",tr:"Gazete okuyor."}, praeteritum:{de:"Sie las ein Buch.",tr:"Bir kitap okudu."}, partizip:{de:"Ich habe das Buch gelesen.",tr:"Kitabı okudum."} } },
  { inf:"schreiben", tr:"yazmak", type:"irregular", praesens:"schreibt", praeteritum:"schrieb", partizip:"geschrieben", aux:"haben",
    ex:{ inf:{de:"Ich muss eine E-Mail schreiben.",tr:"Bir e-posta yazmam lazım."}, praesens:{de:"Er schreibt einen Brief.",tr:"Mektup yazıyor."}, praeteritum:{de:"Sie schrieb ihm täglich.",tr:"Ona her gün yazardı."}, partizip:{de:"Ich habe dir geschrieben.",tr:"Sana yazdım."} } },
  { inf:"sprechen", tr:"konuşmak", type:"irregular", praesens:"spricht", praeteritum:"sprach", partizip:"gesprochen", aux:"haben",
    ex:{ inf:{de:"Ich möchte mit dir sprechen.",tr:"Seninle konuşmak istiyorum."}, praesens:{de:"Er spricht Deutsch.",tr:"Almanca konuşuyor."}, praeteritum:{de:"Sie sprach mit dem Chef.",tr:"Patronla konuştu."}, partizip:{de:"Wir haben lange gesprochen.",tr:"Uzun uzun konuştuk."} } },
  { inf:"essen", tr:"yemek", type:"irregular", praesens:"isst", praeteritum:"aß", partizip:"gegessen", aux:"haben",
    ex:{ inf:{de:"Ich möchte etwas essen.",tr:"Bir şeyler yemek istiyorum."}, praesens:{de:"Er isst gern Pizza.",tr:"Pizza yemeyi sever."}, praeteritum:{de:"Wir aßen im Restaurant.",tr:"Restoranda yedik."}, partizip:{de:"Ich habe schon gegessen.",tr:"Zaten yedim."} } },
  { inf:"trinken", tr:"içmek", type:"irregular", praesens:"trinkt", praeteritum:"trank", partizip:"getrunken", aux:"haben",
    ex:{ inf:{de:"Willst du etwas trinken?",tr:"Bir şey içmek ister misin?"}, praesens:{de:"Er trinkt keinen Alkohol.",tr:"Alkol içmez."}, praeteritum:{de:"Ich trank einen Kaffee.",tr:"Bir kahve içtim."}, partizip:{de:"Ich habe Wasser getrunken.",tr:"Su içtim."} } },
  { inf:"schlafen", tr:"uyumak", type:"irregular", praesens:"schläft", praeteritum:"schlief", partizip:"geschlafen", aux:"haben",
    ex:{ inf:{de:"Ich möchte schlafen.",tr:"Uyumak istiyorum."}, praesens:{de:"Das Baby schläft.",tr:"Bebek uyuyor."}, praeteritum:{de:"Er schlief bis 10 Uhr.",tr:"10'a kadar uyudu."}, partizip:{de:"Ich habe gut geschlafen.",tr:"İyi uyudum."} } },
  { inf:"fahren", tr:"gitmek (araçla)", type:"irregular", praesens:"fährt", praeteritum:"fuhr", partizip:"gefahren", aux:"sein",
    ex:{ inf:{de:"Wir wollen ans Meer fahren.",tr:"Denize gitmek istiyoruz."}, praesens:{de:"Er fährt mit dem Bus.",tr:"Otobüsle gidiyor."}, praeteritum:{de:"Sie fuhr nach Berlin.",tr:"Berlin'e gitti."}, partizip:{de:"Ich bin nach München gefahren.",tr:"Münih'e gittim."} } },
  { inf:"laufen", tr:"koşmak/yürümek", type:"irregular", praesens:"läuft", praeteritum:"lief", partizip:"gelaufen", aux:"sein",
    ex:{ inf:{de:"Ich will schneller laufen.",tr:"Daha hızlı koşmak istiyorum."}, praesens:{de:"Das Kind läuft schon.",tr:"Çocuk artık yürüyor."}, praeteritum:{de:"Er lief zehn Kilometer.",tr:"On kilometre koştu."}, partizip:{de:"Ich bin viel gelaufen.",tr:"Çok yürüdüm."} } },
  { inf:"bleiben", tr:"kalmak", type:"irregular", praesens:"bleibt", praeteritum:"blieb", partizip:"geblieben", aux:"sein",
    ex:{ inf:{de:"Ich möchte zu Hause bleiben.",tr:"Evde kalmak istiyorum."}, praesens:{de:"Er bleibt lange wach.",tr:"Geç vakte kadar uyanık kalıyor."}, praeteritum:{de:"Sie blieb bis Freitag.",tr:"Cuma'ya kadar kaldı."}, partizip:{de:"Wir sind im Hotel geblieben.",tr:"Otelde kaldık."} } },
  { inf:"heißen", tr:"adında olmak", type:"irregular", praesens:"heißt", praeteritum:"hieß", partizip:"geheißen", aux:"haben",
    ex:{ inf:{de:"Wie soll das heißen?",tr:"Bu ne demek?"}, praesens:{de:"Er heißt Max.",tr:"Adı Max."}, praeteritum:{de:"Sie hieß Maria.",tr:"Adı Maria idi."}, partizip:{de:"So hat er immer geheißen.",tr:"Hep böyle adlandırıldı."} } },
  { inf:"fliegen", tr:"uçmak", type:"irregular", praesens:"fliegt", praeteritum:"flog", partizip:"geflogen", aux:"sein",
    ex:{ inf:{de:"Ich hasse zu fliegen.",tr:"Uçmaktan nefret ederim."}, praesens:{de:"Er fliegt nach Paris.",tr:"Paris'e uçuyor."}, praeteritum:{de:"Wir flogen letzte Woche.",tr:"Geçen hafta uçtuk."}, partizip:{de:"Ich bin nach Istanbul geflogen.",tr:"İstanbul'a uçtum."} } },
  { inf:"schwimmen", tr:"yüzmek", type:"irregular", praesens:"schwimmt", praeteritum:"schwamm", partizip:"geschwommen", aux:"sein",
    ex:{ inf:{de:"Ich gehe jetzt schwimmen.",tr:"Yüzmeye gidiyorum."}, praesens:{de:"Sie schwimmt gut.",tr:"İyi yüzüyor."}, praeteritum:{de:"Er schwamm im See.",tr:"Gölde yüzdü."}, partizip:{de:"Ich bin im Meer geschwommen.",tr:"Denizde yüzdüm."} } },
  { inf:"fallen", tr:"düşmek", type:"irregular", praesens:"fällt", praeteritum:"fiel", partizip:"gefallen", aux:"sein",
    ex:{ inf:{de:"Pass auf, nicht zu fallen!",tr:"Düşmemeye dikkat et!"}, praesens:{de:"Der Schnee fällt.",tr:"Kar yağıyor."}, praeteritum:{de:"Er fiel vom Rad.",tr:"Bisikletten düştü."}, partizip:{de:"Das Buch ist gefallen.",tr:"Kitap düştü."} } },
  { inf:"sitzen", tr:"oturmak", type:"irregular", praesens:"sitzt", praeteritum:"saß", partizip:"gesessen", aux:"haben",
    ex:{ inf:{de:"Bitte Platz nehmen und sitzen.",tr:"Buyurun oturun."}, praesens:{de:"Er sitzt am Fenster.",tr:"Pencere kenarında oturuyor."}, praeteritum:{de:"Wir saßen im Garten.",tr:"Bahçede oturduk."}, partizip:{de:"Ich habe lange gesessen.",tr:"Uzun süre oturdum."} } },
  { inf:"stehen", tr:"ayakta durmak", type:"irregular", praesens:"steht", praeteritum:"stand", partizip:"gestanden", aux:"haben",
    ex:{ inf:{de:"Du musst lange stehen.",tr:"Uzun süre ayakta durmalısın."}, praesens:{de:"Er steht vor der Tür.",tr:"Kapının önünde duruyor."}, praeteritum:{de:"Ich stand im Stau.",tr:"Trafikte kaldım."}, partizip:{de:"Das Auto hat dort gestanden.",tr:"Araba orada durmuştu."} } },
  { inf:"liegen", tr:"yatmak/uzanmış olmak", type:"irregular", praesens:"liegt", praeteritum:"lag", partizip:"gelegen", aux:"haben",
    ex:{ inf:{de:"Ich will im Bett liegen.",tr:"Yatakta yatmak istiyorum."}, praesens:{de:"Das Buch liegt auf dem Tisch.",tr:"Kitap masanın üstünde."}, praeteritum:{de:"Er lag krank im Bett.",tr:"Hasta yatıyordu."}, partizip:{de:"Ich habe den ganzen Tag gelegen.",tr:"Bütün gün yattım."} } },
  { inf:"verstehen", tr:"anlamak", type:"irregular", praesens:"versteht", praeteritum:"verstand", partizip:"verstanden", aux:"haben",
    ex:{ inf:{de:"Ich will dich verstehen.",tr:"Seni anlamak istiyorum."}, praesens:{de:"Er versteht kein Türkisch.",tr:"Türkçe anlamıyor."}, praeteritum:{de:"Ich verstand kein Wort.",tr:"Tek kelime anlamadım."}, partizip:{de:"Hast du mich verstanden?",tr:"Beni anladın mı?"} } },
  { inf:"helfen", tr:"yardım etmek (+Dat)", type:"irregular", praesens:"hilft", praeteritum:"half", partizip:"geholfen", aux:"haben",
    ex:{ inf:{de:"Kannst du mir helfen?",tr:"Bana yardım eder misin?"}, praesens:{de:"Er hilft seiner Mutter.",tr:"Annesine yardım ediyor."}, praeteritum:{de:"Sie half mir sehr.",tr:"Bana çok yardım etti."}, partizip:{de:"Du hast mir geholfen.",tr:"Bana yardım ettin."} } },
  { inf:"beginnen", tr:"başlamak", type:"irregular", praesens:"beginnt", praeteritum:"begann", partizip:"begonnen", aux:"haben",
    ex:{ inf:{de:"Wir müssen jetzt beginnen.",tr:"Şimdi başlamamız gerek."}, praesens:{de:"Der Film beginnt um 8.",tr:"Film saat 8'de başlıyor."}, praeteritum:{de:"Die Party begann spät.",tr:"Parti geç başladı."}, partizip:{de:"Der Unterricht hat begonnen.",tr:"Ders başladı."} } },
  { inf:"vergessen", tr:"unutmak", type:"irregular", praesens:"vergisst", praeteritum:"vergaß", partizip:"vergessen", aux:"haben",
    ex:{ inf:{de:"Das darfst du nicht vergessen.",tr:"Bunu unutmamalısın."}, praesens:{de:"Er vergisst alles.",tr:"Her şeyi unutuyor."}, praeteritum:{de:"Ich vergaß den Termin.",tr:"Randevuyu unuttum."}, partizip:{de:"Ich habe meinen Schlüssel vergessen.",tr:"Anahtarımı unuttum."} } },
  { inf:"bekommen", tr:"almak/edinmek", type:"irregular", praesens:"bekommt", praeteritum:"bekam", partizip:"bekommen", aux:"haben",
    ex:{ inf:{de:"Ich will einen Job bekommen.",tr:"Bir iş bulmak istiyorum."}, praesens:{de:"Er bekommt oft Briefe.",tr:"Sık sık mektup alıyor."}, praeteritum:{de:"Sie bekam ein Geschenk.",tr:"Bir hediye aldı."}, partizip:{de:"Ich habe das Paket bekommen.",tr:"Paketi aldım."} } },
  { inf:"gefallen", tr:"hoşuna gitmek (+Dat)", type:"irregular", praesens:"gefällt", praeteritum:"gefiel", partizip:"gefallen", aux:"haben",
    ex:{ inf:{de:"Das muss dir gefallen.",tr:"Bunun hoşuna gitmesi lazım."}, praesens:{de:"Mir gefällt das Kleid.",tr:"Elbise hoşuma gitti."}, praeteritum:{de:"Der Film gefiel ihm.",tr:"Film hoşuna gitti."}, partizip:{de:"Hat es dir gefallen?",tr:"Beğendin mi?"} } },
  { inf:"waschen", tr:"yıkamak", type:"irregular", praesens:"wäscht", praeteritum:"wusch", partizip:"gewaschen", aux:"haben",
    ex:{ inf:{de:"Ich muss die Wäsche waschen.",tr:"Çamaşırları yıkamam lazım."}, praesens:{de:"Er wäscht sein Auto.",tr:"Arabasını yıkıyor."}, praeteritum:{de:"Sie wusch die Teller.",tr:"Tabakları yıkadı."}, partizip:{de:"Ich habe meine Hände gewaschen.",tr:"Ellerimi yıkadım."} } },
  { inf:"schließen", tr:"kapamak", type:"irregular", praesens:"schließt", praeteritum:"schloss", partizip:"geschlossen", aux:"haben",
    ex:{ inf:{de:"Bitte die Tür schließen.",tr:"Lütfen kapıyı kapatın."}, praesens:{de:"Das Geschäft schließt um 20 Uhr.",tr:"Mağaza 20'de kapanıyor."}, praeteritum:{de:"Er schloss das Fenster.",tr:"Pencereyi kapattı."}, partizip:{de:"Ich habe die Tür geschlossen.",tr:"Kapıyı kapattım."} } },
  { inf:"gewinnen", tr:"kazanmak", type:"irregular", praesens:"gewinnt", praeteritum:"gewann", partizip:"gewonnen", aux:"haben",
    ex:{ inf:{de:"Wir wollen gewinnen.",tr:"Kazanmak istiyoruz."}, praesens:{de:"Er gewinnt jedes Spiel.",tr:"Her oyunu kazanıyor."}, praeteritum:{de:"Sie gewann den Preis.",tr:"Ödülü kazandı."}, partizip:{de:"Die Mannschaft hat gewonnen.",tr:"Takım kazandı."} } },
  { inf:"verlieren", tr:"kaybetmek", type:"irregular", praesens:"verliert", praeteritum:"verlor", partizip:"verloren", aux:"haben",
    ex:{ inf:{de:"Ich will nicht verlieren.",tr:"Kaybetmek istemiyorum."}, praesens:{de:"Er verliert oft seine Schlüssel.",tr:"Sık sık anahtarlarını kaybediyor."}, praeteritum:{de:"Wir verloren das Spiel.",tr:"Maçı kaybettik."}, partizip:{de:"Ich habe mein Handy verloren.",tr:"Telefonumu kaybettim."} } },

  // Düzenli fiiller
  { inf:"machen", tr:"yapmak", type:"regular", praesens:"macht", praeteritum:"machte", partizip:"gemacht", aux:"haben",
    ex:{ inf:{de:"Was soll ich machen?",tr:"Ne yapmalıyım?"}, praesens:{de:"Er macht seine Aufgaben.",tr:"Ödevlerini yapıyor."}, praeteritum:{de:"Sie machte einen Fehler.",tr:"Bir hata yaptı."}, partizip:{de:"Ich habe das schon gemacht.",tr:"Bunu zaten yaptım."} } },
  { inf:"sagen", tr:"söylemek", type:"regular", praesens:"sagt", praeteritum:"sagte", partizip:"gesagt", aux:"haben",
    ex:{ inf:{de:"Ich will dir etwas sagen.",tr:"Sana bir şey söylemek istiyorum."}, praesens:{de:"Er sagt die Wahrheit.",tr:"Doğruyu söylüyor."}, praeteritum:{de:"Sie sagte nichts.",tr:"Hiçbir şey söylemedi."}, partizip:{de:"Das habe ich nie gesagt.",tr:"Bunu hiç söylemedim."} } },
  { inf:"hören", tr:"duymak", type:"regular", praesens:"hört", praeteritum:"hörte", partizip:"gehört", aux:"haben",
    ex:{ inf:{de:"Ich will dich hören.",tr:"Sesini duymak istiyorum."}, praesens:{de:"Er hört gern Musik.",tr:"Müzik dinlemeyi sever."}, praeteritum:{de:"Ich hörte ein Geräusch.",tr:"Bir ses duydum."}, partizip:{de:"Hast du das gehört?",tr:"Bunu duydun mu?"} } },
  { inf:"lernen", tr:"öğrenmek", type:"regular", praesens:"lernt", praeteritum:"lernte", partizip:"gelernt", aux:"haben",
    ex:{ inf:{de:"Ich will Deutsch lernen.",tr:"Almanca öğrenmek istiyorum."}, praesens:{de:"Er lernt für die Prüfung.",tr:"Sınava çalışıyor."}, praeteritum:{de:"Sie lernte drei Jahre.",tr:"Üç yıl öğrendi."}, partizip:{de:"Ich habe viel gelernt.",tr:"Çok şey öğrendim."} } },
  { inf:"arbeiten", tr:"çalışmak", type:"regular", praesens:"arbeitet", praeteritum:"arbeitete", partizip:"gearbeitet", aux:"haben",
    ex:{ inf:{de:"Ich muss heute arbeiten.",tr:"Bugün çalışmam lazım."}, praesens:{de:"Er arbeitet in Berlin.",tr:"Berlin'de çalışıyor."}, praeteritum:{de:"Ich arbeitete bis spät.",tr:"Geç saate kadar çalıştım."}, partizip:{de:"Ich habe viel gearbeitet.",tr:"Çok çalıştım."} } },
  { inf:"wohnen", tr:"yaşamak (oturmak)", type:"regular", praesens:"wohnt", praeteritum:"wohnte", partizip:"gewohnt", aux:"haben",
    ex:{ inf:{de:"Ich möchte in Berlin wohnen.",tr:"Berlin'de yaşamak istiyorum."}, praesens:{de:"Er wohnt im Zentrum.",tr:"Merkezde yaşıyor."}, praeteritum:{de:"Sie wohnte bei ihrer Tante.",tr:"Teyzesinin yanında kalıyordu."}, partizip:{de:"Wir haben hier lange gewohnt.",tr:"Burada uzun süre yaşadık."} } },
  { inf:"spielen", tr:"oynamak", type:"regular", praesens:"spielt", praeteritum:"spielte", partizip:"gespielt", aux:"haben",
    ex:{ inf:{de:"Die Kinder wollen spielen.",tr:"Çocuklar oynamak istiyor."}, praesens:{de:"Er spielt Fußball.",tr:"Futbol oynuyor."}, praeteritum:{de:"Sie spielten Karten.",tr:"Kağıt oynadılar."}, partizip:{de:"Ich habe Tennis gespielt.",tr:"Tenis oynadım."} } },
  { inf:"kaufen", tr:"satın almak", type:"regular", praesens:"kauft", praeteritum:"kaufte", partizip:"gekauft", aux:"haben",
    ex:{ inf:{de:"Ich will ein Auto kaufen.",tr:"Bir araba almak istiyorum."}, praesens:{de:"Er kauft Brot.",tr:"Ekmek alıyor."}, praeteritum:{de:"Sie kaufte ein Kleid.",tr:"Bir elbise aldı."}, partizip:{de:"Ich habe Blumen gekauft.",tr:"Çiçek aldım."} } },
  { inf:"kochen", tr:"pişirmek", type:"regular", praesens:"kocht", praeteritum:"kochte", partizip:"gekocht", aux:"haben",
    ex:{ inf:{de:"Kannst du kochen?",tr:"Yemek pişirebilir misin?"}, praesens:{de:"Er kocht jeden Tag.",tr:"Her gün yemek pişiriyor."}, praeteritum:{de:"Sie kochte Suppe.",tr:"Çorba pişirdi."}, partizip:{de:"Ich habe Pasta gekocht.",tr:"Makarna pişirdim."} } },
  { inf:"warten", tr:"beklemek", type:"regular", praesens:"wartet", praeteritum:"wartete", partizip:"gewartet", aux:"haben",
    ex:{ inf:{de:"Ich kann nicht warten.",tr:"Bekleyemem."}, praesens:{de:"Er wartet auf den Bus.",tr:"Otobüsü bekliyor."}, praeteritum:{de:"Sie wartete eine Stunde.",tr:"Bir saat bekledi."}, partizip:{de:"Ich habe lange gewartet.",tr:"Uzun süre bekledim."} } },
  { inf:"suchen", tr:"aramak", type:"regular", praesens:"sucht", praeteritum:"suchte", partizip:"gesucht", aux:"haben",
    ex:{ inf:{de:"Ich muss meinen Pass suchen.",tr:"Pasaportumu aramam lazım."}, praesens:{de:"Er sucht eine Wohnung.",tr:"Daire arıyor."}, praeteritum:{de:"Sie suchte ihr Handy.",tr:"Telefonunu arıyordu."}, partizip:{de:"Ich habe dich überall gesucht.",tr:"Seni her yerde aradım."} } },
  { inf:"öffnen", tr:"açmak", type:"regular", praesens:"öffnet", praeteritum:"öffnete", partizip:"geöffnet", aux:"haben",
    ex:{ inf:{de:"Bitte die Tür öffnen.",tr:"Lütfen kapıyı açın."}, praesens:{de:"Das Geschäft öffnet um 9.",tr:"Mağaza 9'da açılıyor."}, praeteritum:{de:"Er öffnete das Fenster.",tr:"Pencereyi açtı."}, partizip:{de:"Ich habe die Flasche geöffnet.",tr:"Şişeyi açtım."} } },
  { inf:"fragen", tr:"sormak", type:"regular", praesens:"fragt", praeteritum:"fragte", partizip:"gefragt", aux:"haben",
    ex:{ inf:{de:"Darf ich etwas fragen?",tr:"Bir şey sorabilir miyim?"}, praesens:{de:"Er fragt den Lehrer.",tr:"Öğretmene soruyor."}, praeteritum:{de:"Sie fragte nach dem Weg.",tr:"Yolu sordu."}, partizip:{de:"Ich habe nach dir gefragt.",tr:"Seni sordum."} } },
  { inf:"antworten", tr:"cevap vermek", type:"regular", praesens:"antwortet", praeteritum:"antwortete", partizip:"geantwortet", aux:"haben",
    ex:{ inf:{de:"Du musst antworten.",tr:"Cevap vermen lazım."}, praesens:{de:"Er antwortet schnell.",tr:"Hızlı cevap veriyor."}, praeteritum:{de:"Sie antwortete nicht.",tr:"Cevap vermedi."}, partizip:{de:"Ich habe noch nicht geantwortet.",tr:"Henüz cevap vermedim."} } },
  { inf:"zeigen", tr:"göstermek", type:"regular", praesens:"zeigt", praeteritum:"zeigte", partizip:"gezeigt", aux:"haben",
    ex:{ inf:{de:"Kannst du mir den Weg zeigen?",tr:"Bana yolu gösterir misin?"}, praesens:{de:"Er zeigt seine Fotos.",tr:"Fotoğraflarını gösteriyor."}, praeteritum:{de:"Sie zeigte mir die Stadt.",tr:"Bana şehri gösterdi."}, partizip:{de:"Ich habe dir das Haus gezeigt.",tr:"Sana evi gösterdim."} } },
  { inf:"brauchen", tr:"ihtiyacı olmak", type:"regular", praesens:"braucht", praeteritum:"brauchte", partizip:"gebraucht", aux:"haben",
    ex:{ inf:{de:"Ich werde Hilfe brauchen.",tr:"Yardıma ihtiyacım olacak."}, praesens:{de:"Er braucht ein neues Auto.",tr:"Yeni bir arabaya ihtiyacı var."}, praeteritum:{de:"Wir brauchten mehr Zeit.",tr:"Daha fazla vakte ihtiyacımız vardı."}, partizip:{de:"Ich habe Geld gebraucht.",tr:"Paraya ihtiyacım oldu."} } },
  { inf:"glauben", tr:"inanmak", type:"regular", praesens:"glaubt", praeteritum:"glaubte", partizip:"geglaubt", aux:"haben",
    ex:{ inf:{de:"Das ist kaum zu glauben.",tr:"Buna inanmak zor."}, praesens:{de:"Er glaubt an dich.",tr:"Sana inanıyor."}, praeteritum:{de:"Sie glaubte ihm nicht.",tr:"Ona inanmadı."}, partizip:{de:"Das habe ich nie geglaubt.",tr:"Buna hiç inanmadım."} } },
  { inf:"bezahlen", tr:"ödemek", type:"regular", praesens:"bezahlt", praeteritum:"bezahlte", partizip:"bezahlt", aux:"haben",
    ex:{ inf:{de:"Ich möchte bezahlen.",tr:"Ödemek istiyorum."}, praesens:{de:"Er bezahlt mit Karte.",tr:"Kartla ödüyor."}, praeteritum:{de:"Sie bezahlte die Rechnung.",tr:"Hesabı ödedi."}, partizip:{de:"Ich habe schon bezahlt.",tr:"Zaten ödedim."} } },
  { inf:"erklären", tr:"açıklamak", type:"regular", praesens:"erklärt", praeteritum:"erklärte", partizip:"erklärt", aux:"haben",
    ex:{ inf:{de:"Kannst du das erklären?",tr:"Bunu açıklayabilir misin?"}, praesens:{de:"Der Lehrer erklärt die Regel.",tr:"Öğretmen kuralı açıklıyor."}, praeteritum:{de:"Sie erklärte alles ruhig.",tr:"Her şeyi sakince açıkladı."}, partizip:{de:"Er hat mir das erklärt.",tr:"Bunu bana açıkladı."} } },
  { inf:"lieben", tr:"sevmek", type:"regular", praesens:"liebt", praeteritum:"liebte", partizip:"geliebt", aux:"haben",
    ex:{ inf:{de:"Man muss das Leben lieben.",tr:"Hayatı sevmek lazım."}, praesens:{de:"Er liebt seine Frau.",tr:"Karısını seviyor."}, praeteritum:{de:"Sie liebte ihn sehr.",tr:"Onu çok severdi."}, partizip:{de:"Ich habe dich immer geliebt.",tr:"Seni hep sevdim."} } },
  { inf:"reisen", tr:"seyahat etmek", type:"regular", praesens:"reist", praeteritum:"reiste", partizip:"gereist", aux:"sein",
    ex:{ inf:{de:"Ich will viel reisen.",tr:"Çok seyahat etmek istiyorum."}, praesens:{de:"Er reist gern allein.",tr:"Yalnız seyahat etmeyi sever."}, praeteritum:{de:"Sie reiste nach Italien.",tr:"İtalya'ya gitti."}, partizip:{de:"Ich bin viel gereist.",tr:"Çok gezdim."} } },
  { inf:"duschen", tr:"duş almak", type:"regular", praesens:"duscht", praeteritum:"duschte", partizip:"geduscht", aux:"haben",
    ex:{ inf:{de:"Ich will jetzt duschen.",tr:"Şimdi duş almak istiyorum."}, praesens:{de:"Er duscht jeden Morgen.",tr:"Her sabah duş alır."}, praeteritum:{de:"Sie duschte schnell.",tr:"Hızlıca duş aldı."}, partizip:{de:"Ich habe kalt geduscht.",tr:"Soğuk duş aldım."} } },

  // Ayrılabilen fiiller
  { inf:"aufstehen", tr:"kalkmak (yataktan)", type:"separable", praesens:"steht auf", praeteritum:"stand auf", partizip:"aufgestanden", aux:"sein",
    ex:{ inf:{de:"Ich muss früh aufstehen.",tr:"Erken kalkmam lazım."}, praesens:{de:"Er steht um 6 Uhr auf.",tr:"Saat 6'da kalkıyor."}, praeteritum:{de:"Ich stand spät auf.",tr:"Geç kalktım."}, partizip:{de:"Sie ist schon aufgestanden.",tr:"Zaten kalkmış."} } },
  { inf:"ankommen", tr:"varmak", type:"separable", praesens:"kommt an", praeteritum:"kam an", partizip:"angekommen", aux:"sein",
    ex:{ inf:{de:"Wann wollt ihr ankommen?",tr:"Ne zaman varmak istiyorsunuz?"}, praesens:{de:"Der Zug kommt um 9 an.",tr:"Tren 9'da varıyor."}, praeteritum:{de:"Wir kamen pünktlich an.",tr:"Zamanında vardık."}, partizip:{de:"Ich bin in Berlin angekommen.",tr:"Berlin'e vardım."} } },
  { inf:"abfahren", tr:"hareket etmek", type:"separable", praesens:"fährt ab", praeteritum:"fuhr ab", partizip:"abgefahren", aux:"sein",
    ex:{ inf:{de:"Wann wollen wir abfahren?",tr:"Ne zaman hareket edelim?"}, praesens:{de:"Der Bus fährt um 8 ab.",tr:"Otobüs 8'de kalkıyor."}, praeteritum:{de:"Der Zug fuhr pünktlich ab.",tr:"Tren vaktinde kalktı."}, partizip:{de:"Wir sind schon abgefahren.",tr:"Zaten yola çıktık."} } },
  { inf:"anrufen", tr:"aramak (telefonla)", type:"separable", praesens:"ruft an", praeteritum:"rief an", partizip:"angerufen", aux:"haben",
    ex:{ inf:{de:"Ich muss meine Mutter anrufen.",tr:"Annemi aramam lazım."}, praesens:{de:"Er ruft jeden Abend an.",tr:"Her akşam arıyor."}, praeteritum:{de:"Sie rief mich an.",tr:"Beni aradı."}, partizip:{de:"Ich habe dich gestern angerufen.",tr:"Dün seni aradım."} } },
  { inf:"einkaufen", tr:"alışveriş yapmak", type:"separable", praesens:"kauft ein", praeteritum:"kaufte ein", partizip:"eingekauft", aux:"haben",
    ex:{ inf:{de:"Ich muss noch einkaufen.",tr:"Daha alışveriş yapmam lazım."}, praesens:{de:"Sie kauft samstags ein.",tr:"Cumartesi alışveriş yapar."}, praeteritum:{de:"Wir kauften zusammen ein.",tr:"Birlikte alışveriş yaptık."}, partizip:{de:"Ich habe schon eingekauft.",tr:"Zaten alışveriş yaptım."} } },
  { inf:"mitbringen", tr:"yanında getirmek", type:"separable", praesens:"bringt mit", praeteritum:"brachte mit", partizip:"mitgebracht", aux:"haben",
    ex:{ inf:{de:"Soll ich etwas mitbringen?",tr:"Bir şey getireyim mi?"}, praesens:{de:"Er bringt immer Kuchen mit.",tr:"Her zaman pasta getirir."}, praeteritum:{de:"Sie brachte Blumen mit.",tr:"Çiçek getirdi."}, partizip:{de:"Ich habe Wein mitgebracht.",tr:"Şarap getirdim."} } },
  { inf:"zurückkommen", tr:"geri gelmek", type:"separable", praesens:"kommt zurück", praeteritum:"kam zurück", partizip:"zurückgekommen", aux:"sein",
    ex:{ inf:{de:"Wann willst du zurückkommen?",tr:"Ne zaman dönmek istiyorsun?"}, praesens:{de:"Er kommt morgen zurück.",tr:"Yarın geri dönüyor."}, praeteritum:{de:"Sie kam spät zurück.",tr:"Geç geri döndü."}, partizip:{de:"Ich bin gerade zurückgekommen.",tr:"Az önce döndüm."} } },
  { inf:"ausgehen", tr:"dışarı çıkmak", type:"separable", praesens:"geht aus", praeteritum:"ging aus", partizip:"ausgegangen", aux:"sein",
    ex:{ inf:{de:"Wollen wir heute ausgehen?",tr:"Bugün dışarı çıkalım mı?"}, praesens:{de:"Er geht oft aus.",tr:"Sık sık dışarı çıkıyor."}, praeteritum:{de:"Wir gingen gestern aus.",tr:"Dün dışarı çıktık."}, partizip:{de:"Ich bin am Wochenende ausgegangen.",tr:"Hafta sonu dışarı çıktım."} } },
  { inf:"anfangen", tr:"başlamak", type:"separable", praesens:"fängt an", praeteritum:"fing an", partizip:"angefangen", aux:"haben",
    ex:{ inf:{de:"Wir müssen bald anfangen.",tr:"Yakında başlamamız gerek."}, praesens:{de:"Die Schule fängt um 8 an.",tr:"Okul 8'de başlıyor."}, praeteritum:{de:"Er fing pünktlich an.",tr:"Zamanında başladı."}, partizip:{de:"Ich habe gerade angefangen.",tr:"Az önce başladım."} } },
  { inf:"aufhören", tr:"durmak/sonlandırmak", type:"separable", praesens:"hört auf", praeteritum:"hörte auf", partizip:"aufgehört", aux:"haben",
    ex:{ inf:{de:"Du musst damit aufhören.",tr:"Bunu bırakman lazım."}, praesens:{de:"Der Regen hört auf.",tr:"Yağmur diniyor."}, praeteritum:{de:"Ich hörte mit dem Rauchen auf.",tr:"Sigarayı bıraktım."}, partizip:{de:"Es hat endlich aufgehört.",tr:"Nihayet durdu."} } },
  { inf:"aussehen", tr:"görünmek (dış)", type:"separable", praesens:"sieht aus", praeteritum:"sah aus", partizip:"ausgesehen", aux:"haben",
    ex:{ inf:{de:"Du musst schick aussehen.",tr:"Şık görünmen lazım."}, praesens:{de:"Sie sieht müde aus.",tr:"Yorgun görünüyor."}, praeteritum:{de:"Er sah krank aus.",tr:"Hasta görünüyordu."}, partizip:{de:"Das Essen hat lecker ausgesehen.",tr:"Yemek lezzetli görünüyordu."} } },
  { inf:"einladen", tr:"davet etmek", type:"separable", praesens:"lädt ein", praeteritum:"lud ein", partizip:"eingeladen", aux:"haben",
    ex:{ inf:{de:"Ich möchte dich einladen.",tr:"Seni davet etmek istiyorum."}, praesens:{de:"Er lädt Freunde ein.",tr:"Arkadaşlarını davet ediyor."}, praeteritum:{de:"Sie lud die Familie ein.",tr:"Aileyi davet etti."}, partizip:{de:"Ich habe sie zum Essen eingeladen.",tr:"Onları yemeğe davet ettim."} } },
  { inf:"fernsehen", tr:"televizyon izlemek", type:"separable", praesens:"sieht fern", praeteritum:"sah fern", partizip:"ferngesehen", aux:"haben",
    ex:{ inf:{de:"Ich will heute fernsehen.",tr:"Bugün TV izlemek istiyorum."}, praesens:{de:"Er sieht jeden Abend fern.",tr:"Her akşam TV izler."}, praeteritum:{de:"Wir sahen zusammen fern.",tr:"Birlikte TV izledik."}, partizip:{de:"Ich habe abends ferngesehen.",tr:"Akşam TV izledim."} } },

  // Ek düzensiz & düzenli (iletişim/iş/duygu)
  { inf:"bedeuten", tr:"anlamına gelmek", type:"regular", praesens:"bedeutet", praeteritum:"bedeutete", partizip:"bedeutet", aux:"haben",
    ex:{ inf:{de:"Was soll das bedeuten?",tr:"Bu ne anlama gelmeli?"}, praesens:{de:"Das Wort bedeutet 'Haus'.",tr:"Bu kelime 'ev' demek."}, praeteritum:{de:"Es bedeutete viel für mich.",tr:"Bu benim için çok şey ifade ediyordu."}, partizip:{de:"Das hat nichts bedeutet.",tr:"Hiçbir şey ifade etmedi."} } },
  { inf:"meinen", tr:"demek/sanmak", type:"regular", praesens:"meint", praeteritum:"meinte", partizip:"gemeint", aux:"haben",
    ex:{ inf:{de:"Was willst du damit meinen?",tr:"Bununla ne demek istiyorsun?"}, praesens:{de:"Er meint das ernst.",tr:"Bunu ciddi söylüyor."}, praeteritum:{de:"Ich meinte nur Spaß.",tr:"Sadece şaka yapıyordum."}, partizip:{de:"Das habe ich nicht so gemeint.",tr:"Bunu öyle demek istemedim."} } },
  { inf:"hoffen", tr:"ummak", type:"regular", praesens:"hofft", praeteritum:"hoffte", partizip:"gehofft", aux:"haben",
    ex:{ inf:{de:"Man muss immer hoffen.",tr:"İnsan hep ummalı."}, praesens:{de:"Er hofft auf gute Nachrichten.",tr:"İyi haberler umut ediyor."}, praeteritum:{de:"Sie hoffte auf Hilfe.",tr:"Yardım umuyordu."}, partizip:{de:"Das habe ich gehofft.",tr:"Bunu umuyordum."} } },
  { inf:"erzählen", tr:"anlatmak", type:"regular", praesens:"erzählt", praeteritum:"erzählte", partizip:"erzählt", aux:"haben",
    ex:{ inf:{de:"Kannst du mir das erzählen?",tr:"Bunu bana anlatabilir misin?"}, praesens:{de:"Er erzählt eine Geschichte.",tr:"Bir hikaye anlatıyor."}, praeteritum:{de:"Sie erzählte alles.",tr:"Her şeyi anlattı."}, partizip:{de:"Er hat mir davon erzählt.",tr:"Bana bundan bahsetti."} } },
  { inf:"benutzen", tr:"kullanmak", type:"regular", praesens:"benutzt", praeteritum:"benutzte", partizip:"benutzt", aux:"haben",
    ex:{ inf:{de:"Darf ich dein Handy benutzen?",tr:"Telefonunu kullanabilir miyim?"}, praesens:{de:"Er benutzt das Wörterbuch.",tr:"Sözlüğü kullanıyor."}, praeteritum:{de:"Ich benutzte ein altes Auto.",tr:"Eski bir araba kullanıyordum."}, partizip:{de:"Ich habe diese App benutzt.",tr:"Bu uygulamayı kullandım."} } },
  { inf:"entscheiden", tr:"karar vermek", type:"irregular", praesens:"entscheidet", praeteritum:"entschied", partizip:"entschieden", aux:"haben",
    ex:{ inf:{de:"Du musst selbst entscheiden.",tr:"Kendin karar vermelisin."}, praesens:{de:"Er entscheidet schnell.",tr:"Hızlı karar veriyor."}, praeteritum:{de:"Sie entschied sich dagegen.",tr:"Aleyhinde karar verdi."}, partizip:{de:"Ich habe mich entschieden.",tr:"Kararımı verdim."} } },
  { inf:"erlauben", tr:"izin vermek", type:"regular", praesens:"erlaubt", praeteritum:"erlaubte", partizip:"erlaubt", aux:"haben",
    ex:{ inf:{de:"Das kann ich nicht erlauben.",tr:"Buna izin veremem."}, praesens:{de:"Er erlaubt es nicht.",tr:"Buna izin vermiyor."}, praeteritum:{de:"Sie erlaubte mir zu gehen.",tr:"Gitmeme izin verdi."}, partizip:{de:"Er hat es mir erlaubt.",tr:"Bana izin verdi."} } },
  { inf:"erhalten", tr:"almak/elde etmek", type:"irregular", praesens:"erhält", praeteritum:"erhielt", partizip:"erhalten", aux:"haben",
    ex:{ inf:{de:"Ich möchte eine Nachricht erhalten.",tr:"Bir haber almak istiyorum."}, praesens:{de:"Er erhält ein Gehalt.",tr:"Maaş alıyor."}, praeteritum:{de:"Wir erhielten die Einladung.",tr:"Daveti aldık."}, partizip:{de:"Ich habe den Brief erhalten.",tr:"Mektubu aldım."} } },
  { inf:"erleben", tr:"yaşamak/deneyimlemek", type:"regular", praesens:"erlebt", praeteritum:"erlebte", partizip:"erlebt", aux:"haben",
    ex:{ inf:{de:"Man muss viel erleben.",tr:"İnsan çok şey yaşamalı."}, praesens:{de:"Sie erlebt etwas Neues.",tr:"Yeni bir şey yaşıyor."}, praeteritum:{de:"Er erlebte einen Unfall.",tr:"Bir kaza yaşadı."}, partizip:{de:"Ich habe viel erlebt.",tr:"Çok şey yaşadım."} } },
  { inf:"sich erinnern", tr:"hatırlamak (+an Akk)", type:"regular", praesens:"erinnert sich", praeteritum:"erinnerte sich", partizip:"erinnert", aux:"haben",
    ex:{ inf:{de:"Ich kann mich nicht erinnern.",tr:"Hatırlayamıyorum."}, praesens:{de:"Er erinnert sich an sie.",tr:"Onu hatırlıyor."}, praeteritum:{de:"Sie erinnerte sich an den Tag.",tr:"O günü hatırladı."}, partizip:{de:"Ich habe mich daran erinnert.",tr:"Bunu hatırladım."} } },
  { inf:"erkennen", tr:"tanımak/fark etmek", type:"irregular", praesens:"erkennt", praeteritum:"erkannte", partizip:"erkannt", aux:"haben",
    ex:{ inf:{de:"Kannst du ihn erkennen?",tr:"Onu tanıyabiliyor musun?"}, praesens:{de:"Er erkennt die Gefahr.",tr:"Tehlikeyi fark ediyor."}, praeteritum:{de:"Ich erkannte sie sofort.",tr:"Onu hemen tanıdım."}, partizip:{de:"Ich habe dich nicht erkannt.",tr:"Seni tanımadım."} } },
  { inf:"erwarten", tr:"beklemek (sonuç olarak)", type:"regular", praesens:"erwartet", praeteritum:"erwartete", partizip:"erwartet", aux:"haben",
    ex:{ inf:{de:"Was ist zu erwarten?",tr:"Ne beklenmeli?"}, praesens:{de:"Er erwartet dich um 8.",tr:"Seni 8'de bekliyor."}, praeteritum:{de:"Sie erwartete eine Antwort.",tr:"Bir cevap bekliyordu."}, partizip:{de:"Das habe ich nicht erwartet.",tr:"Bunu beklemiyordum."} } },
  { inf:"üben", tr:"alıştırma yapmak", type:"regular", praesens:"übt", praeteritum:"übte", partizip:"geübt", aux:"haben",
    ex:{ inf:{de:"Ich muss mehr üben.",tr:"Daha çok alıştırma yapmam lazım."}, praesens:{de:"Sie übt jeden Tag Klavier.",tr:"Her gün piyano çalışıyor."}, praeteritum:{de:"Er übte die neuen Wörter.",tr:"Yeni kelimeleri çalıştı."}, partizip:{de:"Ich habe lange geübt.",tr:"Uzun süre alıştırma yaptım."} } },
  { inf:"wiederholen", tr:"tekrarlamak", type:"regular", praesens:"wiederholt", praeteritum:"wiederholte", partizip:"wiederholt", aux:"haben",
    ex:{ inf:{de:"Können Sie das wiederholen?",tr:"Bunu tekrar eder misiniz?"}, praesens:{de:"Er wiederholt die Regel.",tr:"Kuralı tekrarlıyor."}, praeteritum:{de:"Sie wiederholte den Satz.",tr:"Cümleyi tekrarladı."}, partizip:{de:"Ich habe die Lektion wiederholt.",tr:"Dersi tekrarladım."} } },
  { inf:"feiern", tr:"kutlamak", type:"regular", praesens:"feiert", praeteritum:"feierte", partizip:"gefeiert", aux:"haben",
    ex:{ inf:{de:"Wir wollen feiern.",tr:"Kutlamak istiyoruz."}, praesens:{de:"Er feiert seinen Geburtstag.",tr:"Doğum gününü kutluyor."}, praeteritum:{de:"Sie feierten bis spät.",tr:"Geç saate kadar kutladılar."}, partizip:{de:"Wir haben zu Hause gefeiert.",tr:"Evde kutladık."} } },
  { inf:"gratulieren", tr:"tebrik etmek (+Dat)", type:"regular", praesens:"gratuliert", praeteritum:"gratulierte", partizip:"gratuliert", aux:"haben",
    ex:{ inf:{de:"Ich will dir gratulieren.",tr:"Seni tebrik etmek istiyorum."}, praesens:{de:"Er gratuliert mir zum Erfolg.",tr:"Beni başarımdan dolayı tebrik ediyor."}, praeteritum:{de:"Sie gratulierte uns.",tr:"Bizi tebrik etti."}, partizip:{de:"Ich habe dir schon gratuliert.",tr:"Seni zaten tebrik ettim."} } },
  { inf:"unterschreiben", tr:"imzalamak", type:"irregular", praesens:"unterschreibt", praeteritum:"unterschrieb", partizip:"unterschrieben", aux:"haben",
    ex:{ inf:{de:"Bitte hier unterschreiben.",tr:"Lütfen burayı imzalayın."}, praesens:{de:"Er unterschreibt den Vertrag.",tr:"Sözleşmeyi imzalıyor."}, praeteritum:{de:"Sie unterschrieb schnell.",tr:"Hızlıca imzaladı."}, partizip:{de:"Ich habe das Dokument unterschrieben.",tr:"Belgeyi imzaladım."} } },
  { inf:"ausfüllen", tr:"doldurmak (form)", type:"separable", praesens:"füllt aus", praeteritum:"füllte aus", partizip:"ausgefüllt", aux:"haben",
    ex:{ inf:{de:"Sie müssen das Formular ausfüllen.",tr:"Formu doldurmanız gerek."}, praesens:{de:"Er füllt den Antrag aus.",tr:"Başvuruyu dolduruyor."}, praeteritum:{de:"Ich füllte das Formular aus.",tr:"Formu doldurdum."}, partizip:{de:"Ich habe alles ausgefüllt.",tr:"Her şeyi doldurdum."} } },
  { inf:"planen", tr:"planlamak", type:"regular", praesens:"plant", praeteritum:"plante", partizip:"geplant", aux:"haben",
    ex:{ inf:{de:"Wir müssen das planen.",tr:"Bunu planlamamız lazım."}, praesens:{de:"Er plant den Urlaub.",tr:"Tatili planlıyor."}, praeteritum:{de:"Sie plante alles genau.",tr:"Her şeyi titizce planladı."}, partizip:{de:"Ich habe nichts geplant.",tr:"Hiçbir şey planlamadım."} } },
  { inf:"vorbereiten", tr:"hazırlamak", type:"separable", praesens:"bereitet vor", praeteritum:"bereitete vor", partizip:"vorbereitet", aux:"haben",
    ex:{ inf:{de:"Ich muss mich auf die Prüfung vorbereiten.",tr:"Sınava hazırlanmam lazım."}, praesens:{de:"Sie bereitet das Essen vor.",tr:"Yemeği hazırlıyor."}, praeteritum:{de:"Er bereitete sich gut vor.",tr:"İyi hazırlandı."}, partizip:{de:"Ich habe mich gut vorbereitet.",tr:"İyi hazırlandım."} } },
  { inf:"abholen", tr:"almaya gitmek", type:"separable", praesens:"holt ab", praeteritum:"holte ab", partizip:"abgeholt", aux:"haben",
    ex:{ inf:{de:"Kannst du mich abholen?",tr:"Beni alabilir misin?"}, praesens:{de:"Er holt die Kinder ab.",tr:"Çocukları alıyor."}, praeteritum:{de:"Sie holte mich am Bahnhof ab.",tr:"Beni istasyondan aldı."}, partizip:{de:"Ich habe das Paket abgeholt.",tr:"Paketi aldım."} } },
  { inf:"anmelden", tr:"kaydetmek/kayıt olmak", type:"separable", praesens:"meldet an", praeteritum:"meldete an", partizip:"angemeldet", aux:"haben",
    ex:{ inf:{de:"Ich muss mich anmelden.",tr:"Kayıt yaptırmam lazım."}, praesens:{de:"Er meldet sich online an.",tr:"İnternetten kayıt oluyor."}, praeteritum:{de:"Sie meldete ihr Kind an.",tr:"Çocuğunu kaydettirdi."}, partizip:{de:"Ich habe mich beim Amt angemeldet.",tr:"Belediyeye kaydoldum."} } },
  { inf:"aufpassen", tr:"dikkat etmek", type:"separable", praesens:"passt auf", praeteritum:"passte auf", partizip:"aufgepasst", aux:"haben",
    ex:{ inf:{de:"Du musst aufpassen!",tr:"Dikkat etmelisin!"}, praesens:{de:"Er passt auf die Kinder auf.",tr:"Çocuklara bakıyor."}, praeteritum:{de:"Ich passte nicht auf.",tr:"Dikkat etmedim."}, partizip:{de:"Hast du aufgepasst?",tr:"Dikkat ettin mi?"} } },
  { inf:"teilnehmen", tr:"katılmak (+an Dat)", type:"separable", praesens:"nimmt teil", praeteritum:"nahm teil", partizip:"teilgenommen", aux:"haben",
    ex:{ inf:{de:"Ich möchte am Kurs teilnehmen.",tr:"Kursa katılmak istiyorum."}, praesens:{de:"Er nimmt an der Sitzung teil.",tr:"Toplantıya katılıyor."}, praeteritum:{de:"Sie nahm am Wettbewerb teil.",tr:"Yarışmaya katıldı."}, partizip:{de:"Ich habe am Seminar teilgenommen.",tr:"Seminere katıldım."} } },
  { inf:"umziehen", tr:"taşınmak", type:"separable", praesens:"zieht um", praeteritum:"zog um", partizip:"umgezogen", aux:"sein",
    ex:{ inf:{de:"Wir wollen bald umziehen.",tr:"Yakında taşınmak istiyoruz."}, praesens:{de:"Er zieht nach Berlin um.",tr:"Berlin'e taşınıyor."}, praeteritum:{de:"Sie zogen letztes Jahr um.",tr:"Geçen yıl taşındılar."}, partizip:{de:"Ich bin in eine neue Wohnung umgezogen.",tr:"Yeni daireye taşındım."} } },
  { inf:"einschlafen", tr:"uykuya dalmak", type:"separable", praesens:"schläft ein", praeteritum:"schlief ein", partizip:"eingeschlafen", aux:"sein",
    ex:{ inf:{de:"Ich kann nicht einschlafen.",tr:"Uyuyamıyorum."}, praesens:{de:"Das Kind schläft schnell ein.",tr:"Çocuk çabuk uykuya dalıyor."}, praeteritum:{de:"Er schlief im Bus ein.",tr:"Otobüste uyuyakaldı."}, partizip:{de:"Ich bin vor dem Fernseher eingeschlafen.",tr:"TV'nin önünde uyuyakaldım."} } },
  { inf:"aufwachen", tr:"uyanmak", type:"separable", praesens:"wacht auf", praeteritum:"wachte auf", partizip:"aufgewacht", aux:"sein",
    ex:{ inf:{de:"Ich muss früh aufwachen.",tr:"Erken uyanmam lazım."}, praesens:{de:"Er wacht um 6 Uhr auf.",tr:"6'da uyanıyor."}, praeteritum:{de:"Sie wachte spät auf.",tr:"Geç uyandı."}, partizip:{de:"Ich bin erst um 10 aufgewacht.",tr:"10'a kadar uyandım."} } },
  { inf:"aufräumen", tr:"toparlamak/düzenlemek", type:"separable", praesens:"räumt auf", praeteritum:"räumte auf", partizip:"aufgeräumt", aux:"haben",
    ex:{ inf:{de:"Ich muss mein Zimmer aufräumen.",tr:"Odamı toplamam lazım."}, praesens:{de:"Er räumt die Küche auf.",tr:"Mutfağı topluyor."}, praeteritum:{de:"Sie räumte das Haus auf.",tr:"Evi topladı."}, partizip:{de:"Ich habe alles aufgeräumt.",tr:"Her şeyi topladım."} } },
  { inf:"putzen", tr:"temizlemek", type:"regular", praesens:"putzt", praeteritum:"putzte", partizip:"geputzt", aux:"haben",
    ex:{ inf:{de:"Ich muss die Fenster putzen.",tr:"Pencereleri temizlemem lazım."}, praesens:{de:"Sie putzt die Wohnung.",tr:"Evi temizliyor."}, praeteritum:{de:"Er putzte sein Auto.",tr:"Arabasını temizledi."}, partizip:{de:"Ich habe das Bad geputzt.",tr:"Banyoyu temizledim."} } },
  { inf:"reparieren", tr:"tamir etmek", type:"regular", praesens:"repariert", praeteritum:"reparierte", partizip:"repariert", aux:"haben",
    ex:{ inf:{de:"Kannst du das reparieren?",tr:"Bunu tamir edebilir misin?"}, praesens:{de:"Er repariert das Fahrrad.",tr:"Bisikleti tamir ediyor."}, praeteritum:{de:"Sie reparierte die Lampe.",tr:"Lambayı tamir etti."}, partizip:{de:"Ich habe das Auto repariert.",tr:"Arabayı tamir ettim."} } },
  { inf:"berichten", tr:"rapor etmek/anlatmak", type:"regular", praesens:"berichtet", praeteritum:"berichtete", partizip:"berichtet", aux:"haben",
    ex:{ inf:{de:"Ich will darüber berichten.",tr:"Bu konuda rapor vermek istiyorum."}, praesens:{de:"Die Zeitung berichtet darüber.",tr:"Gazete bunu yazıyor."}, praeteritum:{de:"Er berichtete von seiner Reise.",tr:"Seyahatinden bahsetti."}, partizip:{de:"Man hat davon berichtet.",tr:"Bundan bahsedildi."} } },
  { inf:"empfehlen", tr:"tavsiye etmek", type:"irregular", praesens:"empfiehlt", praeteritum:"empfahl", partizip:"empfohlen", aux:"haben",
    ex:{ inf:{de:"Kannst du mir ein Buch empfehlen?",tr:"Bana bir kitap tavsiye edebilir misin?"}, praesens:{de:"Er empfiehlt das Restaurant.",tr:"Restoranı tavsiye ediyor."}, praeteritum:{de:"Sie empfahl mir einen Arzt.",tr:"Bana bir doktor tavsiye etti."}, partizip:{de:"Das hat er mir empfohlen.",tr:"Bunu bana tavsiye etti."} } }
];

const VERB_TYPES = {
  auxiliary: "Yardımcı",
  modal: "Modal",
  irregular: "Düzensiz",
  regular: "Düzenli",
  separable: "Ayrılabilen"
};
